### ISSUE TITLE
Nb de champs de capteurs

### ISSUE THREAD

**Issue by godinoliver** [godinlu/schematics#15]
![image](https://github.com/user-attachments/assets/1f0fa40d-ff91-4992-a7cf-f17cd444b6dc)
1/ Quand l'option 2 champs de capteurs est sélectionnée mettre 2 champs de capteur (au lieu d'1 actuellement) et identique (m^me nb de capteurs) 
2/ Pourquoi pour deuxième champs le libellé est différent ainsi le choix est grisé contre sélectionnable pour l'autre

![image](https://github.com/user-attachments/assets/75841a3e-5632-449d-8012-38fe5cc18469)
La deuxièm eoption : 2eme champs de capteur ne rajoute que le module hydraulique (et pas la casse pression). Idem pour l'option sur échangeur à plaque (un seul échangeur à plaque)

**Comment by godinoliver** [comment]
Super. 

Comme il y a deux champs de capteurs, il faut 2 raccords capteur métal/métal (ou deux raccords capteur métal/joint) et 2 kits de raccordements

**Comment by godinlu** [comment]
C'est bon lorsqu'il y a 2 champs capteurs, voici à quoi ressemble les raccordement:
![image](https://github.com/user-attachments/assets/5ee4ba49-c1dc-4199-bb16-967bf049c1b8)

**Comment by godinoliver** [comment]
Mettre 2 bitubes uniquement pour les 2 options ci dessous
![image](https://github.com/user-attachments/assets/b86e0ad0-586a-4b5d-bfa4-7e03b22aaa25)
retravailler les liens entre flexibile Inox et Raccords au niveau de diametre des DN.

**Comment by godinlu** [comment]
C'est bon les bitubes sont réglé et les liens entre flexibile Inox et Raccords sont plus logique.

**Comment by godinoliver** [comment]
Travailler les liens (au moment de l'ajout coté flexible et coté raccord)

**Comment by godinlu** [comment]
C'est bon normalement les liens marchent bien à l'ajout et à la suppression des 2 cotées.
