### ISSUE TITLE
Devisé l'option ''ON en mode excédent d'énergie''

### ISSUE THREAD

**Issue by godinoliver** [godinlu/schematics#16]
![image](https://github.com/user-attachments/assets/2243d25f-8c6f-451f-a5f3-c8eafd45481d)

Dans le devis : rajouter dans le chapitre ''capteur solaire thermique'' le kit : 1*kitSSC083

**Comment by godinlu** [comment]
L'option est rajouté sous la forme d'une case à coché dans le champ capteur 
![image](https://github.com/user-attachments/assets/88e025b4-9110-4f54-a43f-9c1d3c0f9e68)
