### ISSUE TITLE
Perte de donner lorsque l'on passe de l'onglet devis à l'onglet formulaire. 

### ISSUE THREAD

**Issue by godinoliver** [godinlu/schematics#17]
En partant d'un fichier réinitialisé. Dans l'onglet devis, on passe le nb de capteurs à 2. 
![image](https://github.com/user-attachments/assets/af8a84ff-2bfb-4f79-b7c0-70e3718a5594)
Puis on clique sur l'onglet ''formulaire'' puis on revient en cliquant sur l'onglet ''devis''
Dans le devis le nb de champs est passé à 1. 
![image](https://github.com/user-attachments/assets/29fe866c-555b-421f-b5c0-e077b12670c1)
alors qu'il est toujours à 2 
![image](https://github.com/user-attachments/assets/0d874d5c-a7f8-45ab-a282-421ddebf3416)
Merci de vérifier s''il n'y a pas d'autre cas comme celui là qui peuvent se produire.

**Comment by godinlu** [comment]
C'est tout bon j'ai normalement corriger le bug, et j'ai vérifier pour d'autres cas mais tous à l'air normal.

**Comment by godinoliver** [comment]
ok
