### ISSUE TITLE
nb de champs de capteurs

### ISSUE THREAD

**Issue by godinoliver** [godinlu/schematics#21]
J'ai bien de sélectionné 2 champs de capteurs et pourtant il n'apparait qu'un seul champs dans le devis. Si je baisse le nb avec les fleche, pour le passer à 1 puis l'augmente pour le passer à 2, le nb reste à 1. dans le devis
![image](https://github.com/user-attachments/assets/2e481ec0-8000-4332-b77a-edb7b88bbf69)
![image](https://github.com/user-attachments/assets/7e4bb540-6eb2-4239-804e-18fce9a55776)

**Comment by godinlu** [comment]
C'est réglé le nombre de champs met bien à jour la quantité.
