### ISSUE TITLE
bug schéma : avec l'option APP1 sur tampon avec échangeur, le schéma hydraulique n'apparait pas

### ISSUE THREAD

**Issue by godinoliver** [godinlu/schematics#28]
![image](https://github.com/user-attachments/assets/d5457464-7470-40e6-91da-32a199dab272)
![image](https://github.com/user-attachments/assets/2b48ebcc-ac17-4b0d-b448-d23d324db77b)

**Comment by godinlu** [comment]
c'est bon j'ai rajouter le tampon pour le schéma hydraulique : 
![image](https://github.com/user-attachments/assets/6941dfba-0fb3-4c69-95e2-d45f0c4282a8)
