### ISSUE TITLE
Kit Raccord DN20

### ISSUE THREAD

**Issue by godinlu** [godinlu/schematics#4]
Ci-joint le fichier ([installation-toto-12052024.json](https://github.com/user-attachments/files/16838239/installation-toto-12052024.json)) Le raccord DN25 apparait alors que c’est DN20 et impossible a enlever. 
![unnamed](https://github.com/user-attachments/assets/629c23ad-dde4-45c3-b854-056c05e80d41)

**Comment by godinoliver** [comment]
solutionné
