### ISSUE TITLE
Kit capteur déporté

### ISSUE THREAD

**Issue by godinlu** [godinlu/schematics#5]
Ci-dessous une évolution du kit capteur.
![unnamed](https://github.com/user-attachments/assets/a1b092e6-ccb2-4f9a-98d6-5c69a5a5ac4c)
Merci de faire lorsqu’il y a l’option capteur sur casse pression ou échangeur à plaque, deux menu déroulant.

Un kit capteur sur casse pression est composé de :

- Module solaire 1 colonne (menu déroulant : aucun ou KITSSC197 ou KITSSC189 ou KITSSC190 ) (choix des lignes jaunes)
- +kit casse pression : (menu déroulant : aucun ou KITSSC206 ou KITSSC208 ) (choix orange)

 

Un capteur kit capteur sur échangeur à plaque est composé

- Module solaire 2 colonne (menu déroulant : aucun ou kitSSC199 ou kitSSC191 ou kitSSC192 ou MOD0197 ou MOD0506 ) (choix bleu clair)
- +kit échangeur à plaque : (menu déroulant : aucun KITSSC200 à 205 ou KITSSC210 ) (choix bleu foncé)

 

P.S. :
- Si option sélectionné :  ‘’2 champs sur casse pression’’, rajouter un second menu déroulant pour le second ‘’Module solaire 1 colonne’’ (rem : Il reste une seule casse pression)
- Si option sélectionné :  ‘’2 champs découplé sur échangeur’’, rajouter un second menu déroulant pour le second ‘’Module solaire 2 colonne’’ (rem : Il reste une seule casse pression)
![unnamed](https://github.com/user-attachments/assets/9fc486c2-533a-49ed-be27-af4187f0247a)

**Comment by godinlu** [comment]
Voici ce que j'ai mis en place: 

- Pour 1 champ capteur sur casse pression:
![image](https://github.com/user-attachments/assets/93bb7d2c-1655-426a-877d-d95f09afde68)
- Pour 1 champ capteur sur échangeur:
![image](https://github.com/user-attachments/assets/ee455f45-2c85-4478-878d-fa526ad27386)
- Pour 2 champ capteur sur casse pression:
![image](https://github.com/user-attachments/assets/fcbc721e-fe4d-487b-a8e7-2ff0aba202cd)
- Pour 2 champ capteur sur échangeur: idem que sur casse pression mais avec les choix de échangeur.

Par contre pour les capteurs sur V3V je ne sais pas quoi faire. 
De plus pour l'instant toute les options sont les même pour chaque module (SC1Z, SC1, SC2, SC1K, SC2K)

**Comment by godinoliver** [comment]
Pour l’option V3V 2 champs de capteurs, proposer l'option dans le cadre capteur, .  
Kit V3V grand kv 1" (KVS=13/8, by pass chaudière, 2 champs de capteurs jusqu'à 24 m²)	KITSSC018
Kit V3V grand kv 1"1/4 (KVS = 13/8, by pass chaudière, 2 champs de capteurs ≥ 24 m²) 	KITSSC028

**Comment by godinlu** [comment]
Voici un exemple de 2 champs capteur sur V3V:
![image](https://github.com/user-attachments/assets/86b7d67c-65ba-4355-9a37-5773e1582095)
Et tous les kits apparaissent maintenant dans la partie capteur:
![image](https://github.com/user-attachments/assets/87882adb-6d0e-4557-b72d-0a6447e41503)

**Comment by godinoliver** [comment]
![image](https://github.com/user-attachments/assets/061c712f-ed50-4f56-b652-28587dd0d5e8)
Il apparait deux fois le kit de raccords coudés au lieu de celui au bon diamètre.  
![image](https://github.com/user-attachments/assets/e8b730f7-3306-4650-94a2-e07c8694d749)

Pour une meilleure compréhension, merci de mettre le module solaire juste sous la ligne échangeur à plaque (ou casse pression).

**Comment by godinlu** [comment]
Ce problème est solutionné dans un autre issues : https://github.com/godinlu/schematics/issues/11
Et malheureusement l'ordre est fait de manière automatique et le changé peut relevé d'une grosse mise à jour.
