### ISSUE TITLE
Quantité de capteurs

### ISSUE THREAD

**Issue by godinlu** [godinlu/schematics#6]
Sur la même page ‘’devis’’ j’ai : 2 en nb de champs  (fichier [installation-22042024.json](https://github.com/user-attachments/files/16837896/installation-22042024.json))
![unnamed](https://github.com/user-attachments/assets/a1afa5a7-b216-4bab-9c85-73b02db2f7fe)
Mais 1 dans le devis (cf. .json)
![unnamed](https://github.com/user-attachments/assets/4b64bcb7-5cab-48f6-b1ee-1778e3184797)
Ce bug s’obtient :
-   Modifiant le champs capteur.
-   Puis retournant sur l’onglet ‘’formulaire’’ faire une modification et revenir sur l’onglet devis.
-   Il semble que des paramètres ne soient pas sauvegardés (cela marche pour les ballons par ex.).
-   Merci de contrôler que tous les paramètres soient bien inchangées.

**Comment by godinlu** [comment]
Je n'ai pas réussi à reproduire le bug

**Comment by godinoliver** [comment]
Moi non plus. 

Ok.
