### ISSUE TITLE
libellé du fichier programmation

### ISSUE THREAD

**Issue by godinlu** [godinlu/schematics#7]
Merci de mettre le même texte dans la fiche programmation (cadre rouge ci-dessous) que celui sélectionné du menu déroulant. 
![unnamed](https://github.com/user-attachments/assets/c745f65b-cf25-4786-ba06-10d0157d437f)
![unnamed-1](https://github.com/user-attachments/assets/01d0cf0b-d163-4483-b479-07e9839a79a0)

**Comment by godinlu** [comment]
c'est fait.
![image](https://github.com/user-attachments/assets/cf965493-34e5-45b1-91b6-3f59e30024d9)

**Comment by godinoliver** [comment]
Nickel
