### ISSUE TITLE
option V3V Bypass Appoint 1

### ISSUE THREAD

**Issue by godinlu** [godinlu/schematics#8]
Lorsque l’option ci-dessous est sélectionné:
![unnamed](https://github.com/user-attachments/assets/2d99550b-7fdc-4544-a9fe-9a292e4429d4)
Merci de rajouter dans le devis le Kit :

Pour les SC1z, SC1, SC2 : KITSSC018

Pour les SCK :                     KITSSC053

**Comment by godinlu** [comment]
J'ai rajouté cette option dans l'onglet divers sous la forme d'une case à cocher.
![image](https://github.com/user-attachments/assets/9e5421ce-4d93-4f7d-900c-2b622fe89448)
Je me demande cependant si le placement est judicieux et si le choix de la case à cocher est judicieux. Car j'ai l'impression que plusieurs options ont besoin de cette article.

**Comment by godinoliver** [comment]
mettre l'option dans le cadre module. 
garder le texte : option V3V bypass appoint 1
par défaut sélectionner l'option correspondante au module (coll ou ind)
laisser choix de modif du diamètre.

**Comment by godinlu** [comment]
L'option est maintenant dans le cadre module, sous la forme d'une liste déroulante.
Et elle apparait dans le devis dans la catégorie : "Capteurs solaires thermiques".

**Comment by godinoliver** [comment]
Merci. Peut-elle apparaitre dans le devis dans la catégorie : ''Module de chauffage solaire et ballon ECS''

**Comment by godinoliver** [comment]
Lorsque l’option ci-dessous est sélectionné:
unnamed
Quand 1 seules option V3V sélectionné : Merci de rajouter dans le devis le Kit :
Pour les SC1z, SC1, SC2 : KITSSC069
Pour les SCK : KITSSC0155

Quand les 2 options V3V sélectionné : Merci de rajouter dans le devis le Kit :
Pour les SC1z, SC1, SC2 : KITSSC018
Pour les SCK : KITSSC053

**Comment by godinlu** [comment]
Le kit KITSSC053 à été remplacé par KITSSC028.

**Comment by godinoliver** [comment]
Mettre par défaut la ligne 1'' (inversé les lignes)

**Comment by godinlu** [comment]
C'est bon les lignes ont bien été inversé 
![image](https://github.com/user-attachments/assets/4f8a6940-994a-4f17-bd1e-535144f3524a)
