### ISSUE TITLE
Option S10 ou S11 : décharge sur V3V zone 1

### ISSUE THREAD

**Issue by godinlu** [godinlu/schematics#9]
Merci de repositionner la **décharge sur V3V** zone 1 qui tombe dans le vide:
![unnamed](https://github.com/user-attachments/assets/703909b4-a1ee-4dde-9295-a1b7cd877992)

**Comment by godinlu** [comment]
C'est bon j'ai repositionné toute les options décharge pour le schéma d'exe, et certaine options pour le schéma hydraulique.

**Comment by godinoliver** [comment]
ne marche pas
